version: '3.1'

services:
  nginx:
    image: nginx
    ports:
        - '8080:8080'
    volumes:
        - ./nginx/:/etc/nginx/conf.d/
        - ./logs/nginx:/var/log/nginx
        - ./wordpress:/var/www/html
    links:
        - wordpress
    restart: always
    networks:
      - net1

  wordpress:
    image: wordpress
    restart: always
    links:
      - db
    networks:
        - net1
    ports:
      - 9000:80
    environment:
      - WORDPRESS_DB_HOST=${DB_HOST}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}
    volumes:
      - ./wordpress:/var/www/html
      - type: bind
        source: ./docker-servername.conf
        target: /etc/apache2/conf-enabled/docker-servername.conf

  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

    networks:
        - net1
    volumes:
      - ./db/:/var/lib/mysql/
    command: --default_authentication_plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
 
networks:
  net1:
    driver: bridge
